Update HTML and CSS
vanina123/Trial-1 pull request #2
Opened 2023-02-20 20:13 UTC by vanina123

### **Project Review Exercise**

1. Added Linters
2. Addded Flexbox to CSS

2023-02-20 20:43 UTC, vanina123 reviewed
STATUS: REQUIRED CHANGES ♻️♻️
Hi @vanina123 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there!

almost-there

To highlight 🍾
All linters are passing ✔️
Good commit history ✔️
Follow GitHub flow ✔️
Required changes ♻️ ♻️
 Check the comments under the review.
Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

- [ ] Add More styling to your page.

Cheers and Happy coding!👏👏👏

2023-02-20 20:43 UTC, vanina123 commented on index.html
> +    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore nam amet esse culpa corporis accusamus voluptatem officia fugit ut quas neque cum iure quasi, praesentium possimus saepe ab erro
- [ ] I think It would be better if you redused the spacing /indentation on this line, because it  makes the code scattered and less professional

2023-02-20 20:43 UTC, vanina123 commented on index.html
>  </body>
- I think its best you sematic because its makes your code professional and more readable

2023-02-20 20:43 UTC, vanina123 commented on styles.css
> +    color: lightgreen;
- I suggest you use more classes and id for some properties to work well

2023-02-20 21:02 UTC, Gambit142 requested changes
Hi @vanina123 👋, 

Good job so far!

## Highlights
- Made use of Github's inline comment feature ✔️ 
- Gave a review summary ✔️ 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider the comment tagged [OPTIONAL] under this review 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-02-20 21:02 UTC, Gambit142 commented on index.html
>  </body>
- [ ] Great work using inline comments. For this comment to be professional, kindly consider making the purpose of suggesting this change clear and understandable. 👍 💻 Please take a look at the following example:

#### Example of vague comment: 

> The README is not descriptive, why don't you make it better?

#### Example of clear comment: 

> The README's "Built With" and "Getting Started" sections are currently empty. Why don't you add content, listing the technology used in the project and how to run it, to them so your README is more informative and professional?

2023-02-20 21:02 UTC, Gambit142 commented on styles.css
> +    color: lightgreen;
- [ ] Once again, great work using the inline comments. For this comment to be professional, kindly consider making the purpose of suggesting this change clear and understandable. I would also advise you to give detailed reasons why you are suggesting a change. 😎 👍 Please take a look at the following examples below:

#### Example of vague comment: 

> The README is not descriptive, why don't you make it better?

#### Example of clear comment: 

> The README's "Built With" and "Getting Started" sections are currently empty. Why don't you add content, listing the technology used in the project and how to run it, to them so your README is more informative and professional?


#### Example of unexplained comment:

> Why don't you use an article tag here instead of a div?

#### Example of properly explained comment:

> Why don't you use an article tag for the .first-article element instead of a div, that would improve the HTML structure and make the page more accessible

2023-02-20 21:02 UTC, Gambit142 commented on index.html
> +    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore nam amet esse culpa corporis accusamus voluptatem officia fugit ut quas neque cum iure quasi, praesentium possimus saepe ab erro
- [OPTIONAL] It would be nice to use emojis when making comments. Using an emoji makes your comment sound polite and friendly. It makes it easier to communicate with you as a reviewer. 👍  😎

2023-02-23 20:57 UTC, vanina123 reviewed
Hi @vanina123 .
Nice work, just need little changes you are almost there
Happy coding

2023-02-23 20:57 UTC, vanina123 commented on index.html
> +    </section>
- I think it's best you use the semantics "section" to cover a large part of the HTML file and also to make your work readable and neat. Semantic help to keep your work organized

2023-02-23 20:57 UTC, vanina123 commented on styles.css
> +    color: lightgreen;
- I suggest the use of more classes and id to easily divide the work and also to make the styling much easier to work with. Classes help to easily identify what part of the container to style be it the parent or the child.

2023-02-23 21:06 UTC, AdnanOlarmmi approved these changes
Hi @vanina123,

This is Adnan Is-haq, your beloved code reviewer, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Approved office man](https://user-images.githubusercontent.com/41163571/219113922-5007d6bb-ff59-4916-b6d3-e5aad3cb4051.gif)

## Highlights
- Nice one using GitHub inline comments.
- Nice one give clear and concise reviews.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 21:09 UTC, merged